ALTER TABLE users ADD COLUMN IF NOT EXISTS author_application_status VARCHAR(20) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS author_application_data TEXT DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS rejection_reason TEXT DEFAULT NULL;
SHOW COLUMNS FROM users;
